all:
  children:
    proxmox:
      hosts:
        pm-primary:
          ansible_host: "REDACTED_PROXMOX_IP"
          ansible_user: "REDACTED_PROXMOX_USER"
    linux_originals:
      vars:
        ansible_user: "REDACTED_LINUX_ADMIN_USER"
        ansible_become: true
        ansible_become_method: sudo
      hosts:
        linux-host-01:
          proxmox_vmid: 206
        linux-host-02:
          proxmox_vmid: 207
        linux-host-03:
          proxmox_vmid: 208
        linux-host-04:
          proxmox_vmid: 209
    windows_originals:
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5985
        ansible_user: "REDACTED_WINDOWS_ADMIN_USER"
      hosts:
        windows-host-01:
          proxmox_vmid: 200
        windows-host-02:
          proxmox_vmid: 201
        windows-host-03:
          proxmox_vmid: 202
        windows-host-04:
          proxmox_vmid: 203
        windows-host-05:
          proxmox_vmid: 204
        windows-host-06:
          proxmox_vmid: 205
