---
- name: Ensure qemu-guest-agent present (dnf family)
  ansible.builtin.package:
    name: qemu-guest-agent
    state: latest
  when: ansible_pkg_mgr in ['dnf', 'yum']

- name: Ensure qemu-guest-agent present (apt family)
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

- name: Ensure qemu-guest-agent enabled
  ansible.builtin.service:
    name: qemu-guest-agent
    enabled: true
    state: started

- name: Ensure SSH enabled on Debian family
  ansible.builtin.service:
    name: ssh
    enabled: true
    state: started
  when: ansible_os_family == 'Debian'

- name: Ensure SSH enabled on RedHat family
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: started
  when: ansible_os_family == 'RedHat'

- name: Disable unattended upgrades timers (Debian family)
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - unattended-upgrades
    - apt-daily.timer
    - apt-daily-upgrade.timer
  when: ansible_os_family == 'Debian'

- name: Disable dnf timers (RedHat family)
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - dnf-automatic.timer
    - dnf-makecache.timer
  when: ansible_os_family == 'RedHat'
